// AUTH types
const SET_TOKEN = 'SET_TOKEN'
const RESET_TOKEN = 'RESET_TOKEN'

// USER types
const SET_USER_ID = 'SET_USER_ID'
const SET_USERNAME = 'SET_USERNAME'
const SET_FIRST_NAME = 'SET_FIRST_NAME'
const SET_LAST_NAME = 'SET_LAST_NAME'
const SET_FULLNAME = 'SET_FULLNAME'
const RESET_USER = 'RESET_USER'

// PRODUCT types
const ADD_PRODUCT = 'ADD_PRODUCT'
const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

// CART types
const SET_CART_ITEM = 'SET_CART_ITEM'
const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

// ORDER types
const ADD_ORDER = 'ADD_ORDER'
const REMOVE_ORDER = 'REMOVE_ORDER'

// CUSTOMER types
const ADD_CUSTOMER = 'ADD_CUSTOMER'
const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER'

// ADDRESS types
const ADD_ADDRESS = 'ADD_ADDRESS'
const REMOVE_ADDRESS = 'REMOVE_ADDRESS'

export { SET_TOKEN, RESET_TOKEN,
    SET_USER_ID, SET_USERNAME, 
    SET_FIRST_NAME, SET_LAST_NAME,
    SET_FULLNAME, RESET_USER,
    ADD_PRODUCT, REMOVE_PRODUCT, 
    SET_CART_ITEM, REMOVE_CART_ITEM,
    ADD_ORDER, REMOVE_ORDER,
    ADD_CUSTOMER, REMOVE_CUSTOMER,
    ADD_ADDRESS, REMOVE_ADDRESS }